apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: super-heroes-dev
  description: The rest heroes project
  annotations:
    argocd/app-name: super-heroes-dev
    backstage.io/kubernetes-id: super-heroes
    backstage.io/kubernetes-namespace: super-heroes
    backstage.io/techdocs-ref: url:https://github.com/tqvarnst/quarkus-super-heroes/
    backstage.io/source-location: url:https://github.com/tqvarnst/quarkus-super-heroes/
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
  links:
    - url: https://devspaces.apps.cluster-xxb9k.sandbox2982.opentlc.com/dev-pipelines/ns/super-heroes/
      title: Pipelines
      icon: web
    - url: https://devspaces.apps.cluster-xxb9k.sandbox2982.opentlc.com/k8s/ns/super-heroes/deployments/super-heroes
      title: Deployment
      icon: web
spec:
  type: service
  lifecycle: production
  owner: dev-user
  system: workshop-system-super-heroes
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-super-heroes
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
spec:
  owner: dev-user